apiVersion: v1
data:
  cmd: cd /data && CLI_OPTS='-Xmx4096m' /app/hapi-fhir-cli run-server --allow-external-refs
    --disable-referential-integrity -f dstu2 -p ${PORT:-8080}
kind: ConfigMap
metadata:
  annotations:
    field.cattle.io/creatorId: u-slhmm
  creationTimestamp: "2020-01-09T12:12:00Z"
  labels:
    cattle.io/creator: norman
  name: startup-override
  namespace: hapifhir
  resourceVersion: "217373792"
  selfLink: /api/v1/namespaces/hapifhir/configmaps/startup-override
  uid: 3d5a3bbc-32d9-11ea-ae91-000c29a84a71
-----
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "14"
    field.cattle.io/creatorId: u-slhmm
    field.cattle.io/publicEndpoints: '[{"addresses":["192.168.26.199"],"port":80,"protocol":"HTTP","serviceName":"hapifhir:hapifhir-r2","ingressName":"hapifhir:hapifhir-r2","hostname":"hapifhir-r2.custodix.tech","allNodes":true}]'
  creationTimestamp: "2020-01-09T09:23:02Z"
  generation: 23
  labels:
    cattle.io/creator: norman
    workload.user.cattle.io/workloadselector: deployment-hapifhir-hapifhir-r2
  name: hapifhir-r2
  namespace: hapifhir
  resourceVersion: "236824121"
  selfLink: /apis/apps/v1/namespaces/hapifhir/deployments/hapifhir-r2
  uid: a24d4a53-32c1-11ea-ae91-000c29a84a71
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      workload.user.cattle.io/workloadselector: deployment-hapifhir-hapifhir-r2
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      annotations:
        cattle.io/timestamp: "2020-01-24T09:34:50Z"
        field.cattle.io/ports: '[[{"containerPort":8080,"dnsName":"hapifhir-r2","kind":"ClusterIP","name":"8080tcp02","protocol":"TCP","sourcePort":0}]]'
      creationTimestamp: null
      labels:
        workload.user.cattle.io/workloadselector: deployment-hapifhir-hapifhir-r2
    spec:
      containers:
      - image: smartonfhir/hapi:r2
        imagePullPolicy: Always
        name: hapifhir-r2
        ports:
        - containerPort: 8080
          name: 8080tcp02
          protocol: TCP
        resources:
          requests:
            memory: 5000Mi
        securityContext:
          allowPrivilegeEscalation: false
          capabilities: {}
          privileged: false
          procMount: Default
          readOnlyRootFilesystem: false
          runAsNonRoot: false
        stdin: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        tty: true
        volumeMounts:
        - mountPath: /app/cmd
          name: cmd
          subPath: cmd
        - mountPath: /data
          name: patient-data
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - configMap:
          defaultMode: 448
          items:
          - key: cmd
            mode: 448
            path: cmd
          name: startup-override
          optional: false
        name: cmd
      - name: patient-data
        persistentVolumeClaim:
          claimName: hapifhir-data
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2020-01-09T09:23:02Z"
    lastUpdateTime: "2020-01-24T09:34:53Z"
    message: ReplicaSet "hapifhir-r2-6699d46fc9" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  - lastTransitionTime: "2020-02-21T10:26:13Z"
    lastUpdateTime: "2020-02-21T10:26:13Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  observedGeneration: 23
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
-------
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    field.cattle.io/creatorId: u-slhmm
    field.cattle.io/ingressState: '{"aGFwaWZoaXItcjIvaGFwaWZoaXIvaGFwaWZoaXItcjIuY3VzdG9kaXgudGVjaC8vODA4MA==":""}'
    field.cattle.io/publicEndpoints: '[{"addresses":["192.168.26.199"],"port":80,"protocol":"HTTP","serviceName":"hapifhir:hapifhir-r2","ingressName":"hapifhir:hapifhir-r2","hostname":"hapifhir-r2.custodix.tech","allNodes":true}]'
  creationTimestamp: "2020-01-09T09:25:26Z"
  generation: 1
  labels:
    cattle.io/creator: norman
  name: hapifhir-r2
  namespace: hapifhir
  resourceVersion: "236823866"
  selfLink: /apis/extensions/v1beta1/namespaces/hapifhir/ingresses/hapifhir-r2
  uid: f8766b9c-32c1-11ea-ae91-000c29a84a71
spec:
  rules:
  - host: hapifhir-r2.custodix.tech
    http:
      paths:
      - backend:
          serviceName: hapifhir-r2
          servicePort: 8080
status:
  loadBalancer:
    ingress:
    - ip: 192.168.26.199
    - ip: 192.168.26.226
    - ip: 192.168.26.238
    - ip: 192.168.26.24
    - ip: 192.168.26.241

--------
apiVersion: v1
kind: Service
metadata:
  annotations:
    field.cattle.io/targetWorkloadIds: '["deployment:hapifhir:hapifhir-r2"]'
    workload.cattle.io/targetWorkloadIdNoop: "true"
    workload.cattle.io/workloadPortBased: "true"
  creationTimestamp: "2020-01-09T13:03:32Z"
  labels:
    cattle.io/creator: norman
  name: hapifhir-r2
  namespace: hapifhir
  ownerReferences:
  - apiVersion: apps/v1beta2
    controller: true
    kind: deployment
    name: hapifhir-r2
    uid: a24d4a53-32c1-11ea-ae91-000c29a84a71
  resourceVersion: "217383811"
  selfLink: /api/v1/namespaces/hapifhir/services/hapifhir-r2
  uid: 7033818a-32e0-11ea-9dcb-000c29b7c608
spec:
  clusterIP: 10.43.104.132
  ports:
  - name: 8080tcp2
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    workload.user.cattle.io/workloadselector: deployment-hapifhir-hapifhir-r2
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
------
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    field.cattle.io/creatorId: u-slhmm
    pv.kubernetes.io/bind-completed: "yes"
    pv.kubernetes.io/bound-by-controller: "yes"
    volume.beta.kubernetes.io/storage-provisioner: storage-provisioner
  creationTimestamp: "2020-01-24T09:29:38Z"
  finalizers:
  - kubernetes.io/pvc-protection
  labels:
    cattle.io/creator: norman
  name: hapifhir-data
  namespace: hapifhir
  resourceVersion: "221243963"
  selfLink: /api/v1/namespaces/hapifhir/persistentvolumeclaims/hapifhir-data
  uid: 0ac99809-3e8c-11ea-ae91-000c29a84a71
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 107374182400m
  storageClassName: storage
  volumeMode: Filesystem
  volumeName: pvc-0ac99809-3e8c-11ea-ae91-000c29a84a71
status:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 107374182400m
  phase: Bound
