DELETE FROM usergroup_authority;

DELETE FROM authority;

INSERT INTO authority (id, version, name)
VALUES
(1, 1, 'ManageAccount_View'),
(2, 1, 'ManageAccount_Edit'),
(3, 1, 'ManageUsers_View'),
(4, 1, 'ManageUsers_Edit'),
(5, 1, 'Studies_View'),
(6, 1, 'Studies_ViewAsDRM'),
(7, 1, 'Studies_ViewAsPI'),
(8, 1, 'Studies_ViewAsTP'),
(9, 1, 'Study_Metadata_View'),
(10, 1, 'Study_Query_View'),
(11, 1, 'Study_Protocole_View'),
(12, 1, 'Study_Results_View'),
(13, 1, 'Study_Patients_View'),
(14, 1, 'Study_Patients_Import'),
(15, 1, 'Study_Patients_Update'),
(16, 1, 'Study_PI_View'),
(17, 1, 'Study_PI_Edit'),
(18, 1, 'Study_TP_View'),
(19, 1, 'Study_TP_Edit'),
(20, 1, 'Study_AcceptDecline'),
(21, 1, 'Study_Patients_ViewAsPI'),
(22, 1, 'Study_Patients_ViewAsTP'),
(23, 1, 'Study_Patient_View'),
(24, 1, 'Study_Patient_ViewAsPI'),
(25, 1, 'Study_Patient_ViewAsTP'),
(26, 1, 'Feasibility'),
(27, 1, 'Patient_List_Access');

INSERT INTO usergroup_authority (group_id, authority_id)
VALUES
((SELECT id FROM usergroup WHERE name = 'Administrators'), 1),
((SELECT id FROM usergroup WHERE name = 'Administrators'), 2),
((SELECT id FROM usergroup WHERE name = 'Administrators'), 3),
((SELECT id FROM usergroup WHERE name = 'Administrators'), 4),
((SELECT id FROM usergroup WHERE name = 'Administrators'), 5),
((SELECT id FROM usergroup WHERE name = 'Administrators'), 6),
((SELECT id FROM usergroup WHERE name = 'Administrators'), 7),
((SELECT id FROM usergroup WHERE name = 'Administrators'), 8),
((SELECT id FROM usergroup WHERE name = 'Administrators'), 9),
((SELECT id FROM usergroup WHERE name = 'Administrators'), 10),
((SELECT id FROM usergroup WHERE name = 'Administrators'), 11),
((SELECT id FROM usergroup WHERE name = 'Administrators'), 12),
((SELECT id FROM usergroup WHERE name = 'Administrators'), 13),
((SELECT id FROM usergroup WHERE name = 'Administrators'), 14),
((SELECT id FROM usergroup WHERE name = 'Administrators'), 15),
((SELECT id FROM usergroup WHERE name = 'Administrators'), 16),
((SELECT id FROM usergroup WHERE name = 'Administrators'), 17),
((SELECT id FROM usergroup WHERE name = 'Administrators'), 18),
((SELECT id FROM usergroup WHERE name = 'Administrators'), 19),
((SELECT id FROM usergroup WHERE name = 'Administrators'), 20),
((SELECT id FROM usergroup WHERE name = 'Administrators'), 21),
((SELECT id FROM usergroup WHERE name = 'Administrators'), 22),
((SELECT id FROM usergroup WHERE name = 'Administrators'), 23),
((SELECT id FROM usergroup WHERE name = 'Administrators'), 24),
((SELECT id FROM usergroup WHERE name = 'Administrators'), 25),
((SELECT id FROM usergroup WHERE name = 'Administrators'), 26),
((SELECT id FROM usergroup WHERE name = 'Data Relationship Managers'), 1),
((SELECT id FROM usergroup WHERE name = 'Data Relationship Managers'), 2),
((SELECT id FROM usergroup WHERE name = 'Data Relationship Managers'), 5),
((SELECT id FROM usergroup WHERE name = 'Data Relationship Managers'), 9),
((SELECT id FROM usergroup WHERE name = 'Data Relationship Managers'), 10),
((SELECT id FROM usergroup WHERE name = 'Data Relationship Managers'), 11),
((SELECT id FROM usergroup WHERE name = 'Data Relationship Managers'), 6),
((SELECT id FROM usergroup WHERE name = 'Data Relationship Managers'), 12),
((SELECT id FROM usergroup WHERE name = 'Data Relationship Managers'), 16),
((SELECT id FROM usergroup WHERE name = 'Data Relationship Managers'), 17),
((SELECT id FROM usergroup WHERE name = 'Data Relationship Managers'), 20),
((SELECT id FROM usergroup WHERE name = 'Treating Physicians'), 1),
((SELECT id FROM usergroup WHERE name = 'Treating Physicians'), 2),
((SELECT id FROM usergroup WHERE name = 'Treating Physicians'), 5),
((SELECT id FROM usergroup WHERE name = 'Treating Physicians'), 9),
((SELECT id FROM usergroup WHERE name = 'Treating Physicians'), 10),
((SELECT id FROM usergroup WHERE name = 'Treating Physicians'), 11),
((SELECT id FROM usergroup WHERE name = 'Treating Physicians'), 8),
((SELECT id FROM usergroup WHERE name = 'Treating Physicians'), 13),
((SELECT id FROM usergroup WHERE name = 'Treating Physicians'), 22),
((SELECT id FROM usergroup WHERE name = 'Treating Physicians'), 23),
((SELECT id FROM usergroup WHERE name = 'Treating Physicians'), 25),
((SELECT id FROM usergroup WHERE name = 'Users'), 1),
((SELECT id FROM usergroup WHERE name = 'Users'), 2),
((SELECT id FROM usergroup WHERE name = 'Users'), 5),
((SELECT id FROM usergroup WHERE name = 'Users'), 9),
((SELECT id FROM usergroup WHERE name = 'Users'), 10),
((SELECT id FROM usergroup WHERE name = 'Users'), 11),
((SELECT id FROM usergroup WHERE name = 'Users'), 8),
((SELECT id FROM usergroup WHERE name = 'Users'), 13),
((SELECT id FROM usergroup WHERE name = 'Users'), 22),
((SELECT id FROM usergroup WHERE name = 'Users'), 23),
((SELECT id FROM usergroup WHERE name = 'Users'), 25),
((SELECT id FROM usergroup WHERE name = 'Power Users'), 27);